In [34]:
import numpy as np

In [35]:
a = np.array([[1,2,3],
             [4,5,6]])

In [36]:
b = np.array([[4,5,6],
             [1,2,3]])

In [37]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[4, 5, 6],
        [1, 2, 3]]))

In [39]:
c = a+b

In [41]:
np.sum(a, axis = 0)

array([5, 7, 9])

In [42]:
np.sum(a, axis = 1)

array([ 6, 15])